<a href="https://colab.research.google.com/github/Tanveer132/Dimensionality-Reduction-Techniques-in-ML/blob/main/FST_Practice_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Principal Component Analysis

>1. using numpy

>2. using pca in sklearn.decomposision

In [1]:
import numpy as np
from numpy.linalg import eig
from sklearn.decomposition import PCA

##Using numpy

In [2]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
# get scaled data
m=np.mean(data,axis=0)

scaled_data=m-data
scaled_data

array([[ 2.,  2.],
       [ 0.,  0.],
       [-2., -2.]])

In [4]:
# get covarience matrix
V=np.cov(scaled_data.T)
V 

array([[4., 4.],
       [4., 4.]])

In [5]:
# get eigen vectors and eigen values
values,vectors=eig(V)

In [6]:
values.T

array([8., 0.])

In [7]:
vectors.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [8]:
# get transformed data
P = vectors.T.dot(scaled_data.T)
P.T

array([[ 2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [-2.82842712,  0.        ]])

**Conclusion :** Here dimensions reduced from 2 to 1

##Using pca in sklearn

In [9]:
pca=PCA()
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [10]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [11]:
pca.explained_variance_

array([8., 0.])

In [14]:
P=pca.transform(data)
P

array([[-2.82842712e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 2.82842712e+00,  2.22044605e-16]])