<a href="https://colab.research.google.com/github/Tanveer132/Dimensionality-Reduction-Technoques-in-ML/blob/main/FST_Practice_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Singular Value Decomposition
>**Using numpy.svd**

>**Using TruncatedSVD in sklearn.decomposition**

>**Using randomized_svd in sklearn.utils.extmath**

##1. using numpy

In [1]:
import numpy as np
from numpy.linalg import svd

In [7]:
A=np.array([[1,2,3],[2,-3,4],[3,4,-5]])
print(A)

[[ 1  2  3]
 [ 2 -3  4]
 [ 3  4 -5]]


In [4]:
U,S,Vt=svd(A)
print("Left Singular Matrix :\n",U)
print("\n singular matrix :\n",np.diag(S))
print("\n Right singular matrix :\n",Vt)

Left Singular Matrix :
 [[ 0.1419502   0.75380251  0.64158547]
 [ 0.56260227  0.47184715 -0.6788512 ]
 [-0.81445001  0.4573205  -0.35711221]]

 singular matrix :
 [[8.28597167 0.         0.        ]
 [0.         4.07196614 0.        ]
 [0.         0.         2.78599448]]

 Right singular matrix :
 [[-0.1419502  -0.56260227  0.81445001]
 [ 0.75380251  0.47184715  0.4573205 ]
 [-0.64158547  0.6788512   0.35711221]]


##2. Using TruncatedSVD

In [15]:
from sklearn.decomposition import TruncatedSVD
SVD=TruncatedSVD(n_components=2)            #n_components=2 is less than dimention of data,,,,min should be 2
A_trans=SVD.fit_transform(A)
print("\n Original matrix :\n",A)
print("\n singular values :\n",SVD.singular_values_)
print("\n matrix after reducing 2 components :\n",A_trans)


 Original matrix :
 [[ 1  2  3]
 [ 2 -3  4]
 [ 3  4 -5]]

 singular values :
 [8.28597167 4.07196614]

 matrix after reducing 2 components :
 [[-1.17619531  3.06945831]
 [-4.66170648  1.9213456 ]
 [ 6.74850975  1.86219361]]


##2. After Randomized svd

In [16]:
from sklearn.utils.extmath import randomized_svd
U,S,Vt=randomized_svd(A,n_components=2)

print("Left Singular Matrix :\n",U)
print("\n singular matrix :\n",np.diag(S))
print("\n Right singular matrix :\n",Vt)

Left Singular Matrix :
 [[-0.1419502   0.75380251]
 [-0.56260227  0.47184715]
 [ 0.81445001  0.4573205 ]]

 singular matrix :
 [[8.28597167 0.        ]
 [0.         4.07196614]]

 Right singular matrix :
 [[ 0.1419502   0.56260227 -0.81445001]
 [ 0.75380251  0.47184715  0.4573205 ]]
